[main]
logging = "warn"
source = "udp://127.0.0.1:6789"
capture = "ffmpeg"
cuda-enable = true
datastorage = "boltdb"

[processing]
pipeline = [
    "facedetectyn.wasm",
    "face-counter.wasm",
    "faceblur.wasm"
]

[models]
download = true

[configuration]
detect-draw-faces="false"
