[main]
logging = "warn"
source = "udp://127.0.0.1:6789"
capture = "ffmpeg"

[processing]
pipeline = [
    "facedetectyn.wasm"
]
download = true

[models]
download = true

[server]
mcp-enable = false
mcp-port = ":5001"
