main:
  logging: "info"
  destination: ":8080"
  cuda-enable: true

processing:
  pipeline:
    - "ollama.wasm"
    - "style-transfer.wasm"
    - "captions.wasm"

configuration:
  ollama-model: "qnguyen3/nanollava"
  ollama-prompt: "Describe this scene in a very complimentary way using 7 words or less."
  caption-line-height: "30"
  caption-size: "0.8"

models:
  download: true
