[main]
logging = "warn"
destination = ":8080"
cuda-enable = true

[processing]
pipeline = [
    "ollama.wasm",
    "mosaic.wasm",
    "captions.wasm"
]
configuration = [
    "model=qnguyen3/nanollava"
]

[models]
download = true

[server]
mcp-enable = false
mcp-port = ":5001"
